#!/usr/bin/env python3
"""
ZCODE catalog generator — SPEC-001 §10 (300 curated packages) + §19 schema.

Menghasilkan:
  app/src/main/assets/package_catalog/packages.json       — katalog 300 package
  app/src/main/assets/package_catalog/stdlib.json         — index stdlib (~305 nama, Python 3.11)
  app/src/main/assets/package_catalog/smoke-tests.json    — manifest smoke test (package utama)
  app/src/main/assets/package_catalog/tested-manifest.json— versi tested ZCODE (prioritas wheel)

Keputusan forum: katalog = knowledge base — INCOMPATIBLE/UNAVAILABLE TETAP tampil
dengan penjelasan. Status TESTED hanya untuk yang benar-benar diuji ZCODE.

Pemakaian:  python3 tools/generate_catalog.py [--check]
"""
import argparse
import json
import sys
import sysconfig
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "app/src/main/assets/package_catalog"

# ---------------------------------------------------------------------------
# Kategori (SPEC §10) — jumlah target
# ---------------------------------------------------------------------------
CATEGORY_TARGETS = {
    "Data / Math / Science": 45,
    "Web / API / Networking": 35,
    "Utilities / CLI / Terminal": 35,
    "Files / Office / Document": 30,
    "Database / Storage": 25,
    "Automation / Scripting": 25,
    "Testing / Quality / Debugging": 25,
    "Image / Audio / Media": 25,
    "AI / ML / NLP": 25,
    "GUI / Games / App Framework": 15,
    "Security / Cryptography": 15,
}
TOTAL_TARGET = sum(CATEGORY_TARGETS.values())  # 300

# type: pure | native | gui
# status: TESTED | COMPATIBLE | EXPERIMENTAL | INCOMPATIBLE | UNAVAILABLE
# fmt: (name, import_name, category, type, status, short_desc)
CATALOG = [
    # ---------------- Data / Math / Science (45) ----------------
    ("numpy", "numpy", "Data / Math / Science", "native", "TESTED",
     "Komputasi numerik & array multi-dimensi — fondasi hampir semua stack sains."),
    ("matplotlib", "matplotlib", "Data / Math / Science", "native", "TESTED",
     "Plot & visualisasi data (backend Agg → savefig PNG)."),
    ("pandas", "pandas", "Data / Math / Science", "native", "EXPERIMENTAL",
     "Analisis data tabular (DataFrame). Berat di RAM kecil."),
    ("scipy", "scipy", "Data / Math / Science", "native", "EXPERIMENTAL",
     "Algoritma sains: optimasi, integrasi, statistik, sinyal."),
    ("sympy", "sympy", "Data / Math / Science", "pure", "COMPATIBLE",
     "Matematika simbolik murni-Python."),
    ("scikit-learn", "scikit-learn", "Data / Math / Science", "native", "EXPERIMENTAL",
     "Machine learning klasik (regresi, klasifikasi, clustering)."),
    ("scikit-image", "skimage", "Data / Math / Science", "native", "EXPERIMENTAL",
     "Pemrosesan citra ilmiah."),
    ("statsmodels", "statsmodels", "Data / Math / Science", "native", "EXPERIMENTAL",
     "Model statistik & ekonometrika."),
    ("seaborn", "seaborn", "Data / Math / Science", "pure", "COMPATIBLE",
     "Visualisasi statistik di atas matplotlib."),
    ("plotly", "plotly", "Data / Math / Science", "pure", "EXPERIMENTAL",
     "Plot interaktif (output HTML/JSON)."),
    ("bokeh", "bokeh", "Data / Math / Science", "pure", "TESTED",
     "Visualisasi interaktif berbasis browser; v3.3.4 teruji di ARMv7."),
    ("xarray", "xarray", "Data / Math / Science", "pure", "COMPATIBLE",
     "Array berlabel untuk data multidimensi."),
    ("numba", "numba", "Data / Math / Science", "native", "EXPERIMENTAL",
     "JIT compiler — butuh LLVM; berat & belum tentu ada wheel Android."),
    ("networkx", "networkx", "Data / Math / Science", "pure", "COMPATIBLE",
     "Struktur graf & jaringan."),
    ("nltk", "nltk", "Data / Math / Science", "pure", "EXPERIMENTAL",
     "Natural language toolkit (data model terpisah)."),
    ("mpmath", "mpmath", "Data / Math / Science", "pure", "COMPATIBLE",
     "Aritmetika presisi sewenang-wenang."),
    ("lmfit", "lmfit", "Data / Math / Science", "pure", "COMPATIBLE",
     "Curve fitting berbasis scipy.optimize."),
    ("bottleneck", "bottleneck", "Data / Math / Science", "native", "EXPERIMENTAL",
     "Akselerasi fungsi numpy (C extension)."),
    ("numexpr", "numexpr", "Data / Math / Science", "native", "EXPERIMENTAL",
     "Evaluasi ekspresi array berkinerja tinggi."),
    ("dask", "dask", "Data / Math / Science", "pure", "EXPERIMENTAL",
     "Komputasi paralel & array chunked (berat)."),
    ("h5py", "h5py", "Data / Math / Science", "native", "EXPERIMENTAL",
     "Baca/tulis HDF5 — butuh libhdf5 native."),
    ("netcdf4", "netCDF4", "Data / Math / Science", "native", "INCOMPATIBLE",
     "Butuh libnetcdf native; kemungkinan tidak ada wheel Android."),
    ("cvxpy", "cvxpy", "Data / Math / Science", "pure", "EXPERIMENTAL",
     "Optimisasi convex (dependensi berat)."),
    ("pulp", "pulp", "Data / Math / Science", "pure", "COMPATIBLE",
     "Linear programming (solver default bawaan)."),
    ("simpy", "simpy", "Data / Math / Science", "pure", "COMPATIBLE",
     "Simulasi event-discrete."),
    ("polars", "polars", "Data / Math / Science", "native", "EXPERIMENTAL",
     "DataFrame Rust berkinerja tinggi — cek ketersediaan wheel Android."),
    ("pyarrow", "pyarrow", "Data / Math / Science", "native", "EXPERIMENTAL",
     "Arrow / Parquet — native besar."),
    ("sktime", "sktime", "Data / Math / Science", "pure", "EXPERIMENTAL",
     "Time series ML (dependensi banyak)."),
    ("tslearn", "tslearn", "Data / Math / Science", "pure", "EXPERIMENTAL",
     "Time series ML di atas scikit-learn."),
    ("lifelines", "lifelines", "Data / Math / Science", "pure", "COMPATIBLE",
     "Survival analysis."),
    ("pydicom", "pydicom", "Data / Math / Science", "pure", "COMPATIBLE",
     "Baca/tulis file DICOM (medis)."),
    ("openpyxl", "openpyxl", "Data / Math / Science", "pure", "TESTED",
     "Baca/tulis Excel .xlsx — standar untuk data tabular."),
    ("tabulate", "tabulate", "Data / Math / Science", "pure", "COMPATIBLE",
     "Render tabel teks dari data."),
    ("prettytable", "prettytable", "Data / Math / Science", "pure", "COMPATIBLE",
     "Tabel ASCII sederhana."),
    ("periodictable", "periodictable", "Data / Math / Science", "pure", "COMPATIBLE",
     "Data tabel periodik."),
    ("quantities", "quantities", "Data / Math / Science", "pure", "COMPATIBLE",
     "Unit & dimensi fisika."),
    ("uncertainties", "uncertainties", "Data / Math / Science", "pure", "COMPATIBLE",
     "Angka dengan ketidakpastian (error propagation)."),
    ("peakutils", "peakutils", "Data / Math / Science", "pure", "COMPATIBLE",
     "Deteksi puncak pada data 1D."),
    ("pint", "pint", "Data / Math / Science", "pure", "COMPATIBLE",
     "Unit conversion Python."),
    ("fortranformat", "fortranformat", "Data / Math / Science", "pure", "COMPATIBLE",
     "Baca/tulis format Fortran."),
    ("hyperopt", "hyperopt", "Data / Math / Science", "pure", "EXPERIMENTAL",
     "Hyperparameter optimization (distributed)."),
    ("optuna", "optuna", "Data / Math / Science", "pure", "EXPERIMENTAL",
     "Hyperparameter optimization modern."),
    ("emcee", "emcee", "Data / Math / Science", "pure", "EXPERIMENTAL",
     "MCMC ensemble sampler."),
    ("pykalman", "pykalman", "Data / Math / Science", "pure", "COMPATIBLE",
     "Kalman filter."),
    ("arviz", "arviz", "Data / Math / Science", "pure", "EXPERIMENTAL",
     "Visualisasi & diagnostik Bayesian (butuh matplotlib/xarray)."),

    # ---------------- Web / API / Networking (35) ----------------
    ("requests", "requests", "Web / API / Networking", "pure", "TESTED",
     "HTTP client standar, ringan & handal."),
    ("httpx", "httpx", "Web / API / Networking", "pure", "TESTED",
     "HTTP client modern sync/async."),
    ("urllib3", "urllib3", "Web / API / Networking", "pure", "COMPATIBLE",
     "HTTP library berfitur lengkap (dep requests)."),
    ("flask", "flask", "Web / API / Networking", "pure", "TESTED",
     "Micro web framework (jalur App Mode Flask+WebView)."),
    ("beautifulsoup4", "bs4", "Web / API / Networking", "pure", "TESTED",
     "Parsing HTML/XML yang ramah."),
    ("tqdm", "tqdm", "Web / API / Networking", "pure", "TESTED",
     "Progress bar di terminal."),
    ("lxml", "lxml", "Web / API / Networking", "native", "EXPERIMENTAL",
     "Parsing XML/HTML cepat (C extension — cek wheel Chaquopy)."),
    ("aiohttp", "aiohttp", "Web / API / Networking", "native", "EXPERIMENTAL",
     "HTTP client/server async (native, agak berat)."),
    ("fastapi", "fastapi", "Web / API / Networking", "pure", "EXPERIMENTAL",
     "Web framework modern + uvicorn."),
    ("uvicorn", "uvicorn", "Web / API / Networking", "pure", "COMPATIBLE",
     "ASGI server murni-Python."),
    ("waitress", "waitress", "Web / API / Networking", "pure", "COMPATIBLE",
     "WSGI server murni-Python (keluarga ZABACODE)."),
    ("websockets", "websockets", "Web / API / Networking", "pure", "COMPATIBLE",
     "WebSocket client/server."),
    ("gunicorn", "gunicorn", "Web / API / Networking", "pure", "COMPATIBLE",
     "WSGI server (Unix-only — sebagian fitur tidak jalan di Android)."),
    ("werkzeug", "werkzeug", "Web / API / Networking", "pure", "COMPATIBLE",
     "WSGI utility (dep Flask)."),
    ("jinja2", "jinja2", "Web / API / Networking", "pure", "COMPATIBLE",
     "Template engine (dep Flask)."),
    ("itsdangerous", "itsdangerous", "Web / API / Networking", "pure", "COMPATIBLE",
     "Signing data (dep Flask)."),
    ("click", "click", "Web / API / Networking", "pure", "COMPATIBLE",
     "CLI framework (dep Flask)."),
    ("sanic", "sanic", "Web / API / Networking", "pure", "EXPERIMENTAL",
     "Web server async (butuh uvloop? tidak di Android)."),
    ("tornado", "tornado", "Web / API / Networking", "pure", "COMPATIBLE",
     "Web framework non-blocking."),
    ("feedparser", "feedparser", "Web / API / Networking", "pure", "COMPATIBLE",
     "Parsing RSS/Atom."),
    ("youtube_dl", "youtube_dl", "Web / API / Networking", "pure", "EXPERIMENTAL",
     "Download video (legal: hanya konten berizin)."),
    ("yt_dlp", "yt_dlp", "Web / API / Networking", "pure", "EXPERIMENTAL",
     "Fork aktif youtube-dl."),
    ("praw", "praw", "Web / API / Networking", "pure", "COMPATIBLE",
     "Reddit API wrapper."),
    ("tweepy", "tweepy", "Web / API / Networking", "pure", "COMPATIBLE",
     "Twitter/X API wrapper."),
    ("twilio", "twilio", "Web / API / Networking", "pure", "COMPATIBLE",
     "Twilio API (SMS/voice)."),
    ("sendgrid", "sendgrid", "Web / API / Networking", "pure", "COMPATIBLE",
     "SendGrid email API."),
    ("stripe", "stripe", "Web / API / Networking", "pure", "COMPATIBLE",
     "Stripe payment API."),
    ("telegram", "telegram", "Web / API / Networking", "pure", "COMPATIBLE",
     "Telegram Bot API wrapper."),
    ("discord.py", "discord", "Web / API / Networking", "pure", "COMPATIBLE",
     "Discord bot library."),
    ("slack_sdk", "slack_sdk", "Web / API / Networking", "pure", "COMPATIBLE",
     "Slack SDK."),
    ("selenium", "selenium", "Web / API / Networking", "pure", "INCOMPATIBLE",
     "Butuh browser + driver — di luar jangkauan Android in-process."),
    ("playwright", "playwright", "Web / API / Networking", "pure", "INCOMPATIBLE",
     "Butuh browser binary — tidak didukung di ZCODE."),
    ("pyquery", "pyquery", "Web / API / Networking", "pure", "COMPATIBLE",
     "jQuery-style HTML parsing (dep lxml)."),
    ("html5lib", "html5lib", "Web / API / Networking", "pure", "COMPATIBLE",
     "Parser HTML sesuai spesifikasi WHATWG."),
    ("requests_html", "requests_html", "Web / API / Networking", "pure", "INCOMPATIBLE",
     "Bergantung pada pyppeteer/Chrome — tidak jalan di Android."),

    # ---------------- Utilities / CLI / Terminal (35) ----------------
    ("rich", "rich", "Utilities / CLI / Terminal", "pure", "TESTED",
     "Terminal rich text & tabel cantik."),
    ("colorama", "colorama", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "ANSI color lintas platform."),
    ("python-dateutil", "dateutil", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Ekstensi datetime (dep pandas)."),
    ("pytz", "pytz", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Timezone database."),
    ("tzdata", "tzdata", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "IANA timezone data."),
    ("pydantic", "pydantic", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Validasi data & settings via type hints (pydantic-core native)."),
    ("regex", "regex", "Utilities / CLI / Terminal", "native", "EXPERIMENTAL",
     "Regex tingkat lanjut (C extension — cek wheel)."),
    ("pyyaml", "yaml", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "YAML parser."),
    ("toml", "toml", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "TOML parser."),
    ("tomli", "tomli", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "TOML 1.0 parser (Python 3.11: gunakan tomllib bawaan)."),
    ("certifi", "certifi", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "CA bundle untuk HTTPS (penting di Android)."),
    ("six", "six", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Kompatibilitas Py2/3 (dep lama)."),
    ("typing_extensions", "typing_extensions", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Ekstensi typing."),
    ("python-dotenv", "dotenv", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Baca file .env."),
    ("platformdirs", "platformdirs", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Lokasi direktori per-platform."),
    ("filelock", "filelock", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "File locking lintas platform."),
    ("psutil", "psutil", "Utilities / CLI / Terminal", "native", "EXPERIMENTAL",
     "Info proses/sistem (C extension — cek wheel Android)."),
    ("humanize", "humanize", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Format angka/data ramah manusia."),
    ("inflect", "inflect", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Pluralisasi kata Inggris."),
    ("unidecode", "unidecode", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Transliterasi Unicode → ASCII."),
    ("textdistance", "textdistance", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "30+ algoritma jarak string."),
    ("fuzzywuzzy", "fuzzywuzzy", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Fuzzy string matching (dep python-Levenshtein opsional)."),
    ("more-itertools", "more_itertools", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Ekstensi itertools."),
    ("toolz", "toolz", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Fungsi utilitas fungsional."),
    ("boltons", "boltons", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Koleksi utilitas Python murni."),
    ("dateparser", "dateparser", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Parse tanggal dari teks natural."),
    ("pendulum", "pendulum", "Utilities / CLI / Terminal", "pure", "EXPERIMENTAL",
     "Datetime modern (pendulum sudah pure sejak 3.0)."),
    ("arrow", "arrow", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Datetime ramah."),
    ("croniter", "croniter", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Parse/iterasi ekspresi cron."),
    ("schedule", "schedule", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Penjadwalan job sederhana."),
    ("watchdog", "watchdog", "Utilities / CLI / Terminal", "native", "EXPERIMENTAL",
     "File system watcher (native)."),
    ("pathlib2", "pathlib2", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Backport pathlib (untuk kode lama)."),
    ("retry", "retry", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Dekorator retry."),
    ("tenacity", "tenacity", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Retry library modern."),
    ("colorlog", "colorlog", "Utilities / CLI / Terminal", "pure", "COMPATIBLE",
     "Logging berwarna."),

    # ---------------- Files / Office / Document (30) ----------------
    ("xlsxwriter", "xlsxwriter", "Files / Office / Document", "pure", "COMPATIBLE",
     "Tulis Excel .xlsx berfitur lengkap."),
    ("python-docx", "docx", "Files / Office / Document", "pure", "COMPATIBLE",
     "Baca/tulis Word .docx."),
    ("python-pptx", "pptx", "Files / Office / Document", "pure", "COMPATIBLE",
     "Baca/tulis PowerPoint .pptx."),
    ("reportlab", "reportlab", "Files / Office / Document", "pure", "COMPATIBLE",
     "Generate PDF."),
    ("fpdf2", "fpdf", "Files / Office / Document", "pure", "COMPATIBLE",
     "PDF sederhana (fpdf2)."),
    ("pypdf", "pypdf", "Files / Office / Document", "pure", "COMPATIBLE",
     "Baca/tulis PDF (pengganti PyPDF2)."),
    ("pdfplumber", "pdfplumber", "Files / Office / Document", "pure", "EXPERIMENTAL",
     "Ekstraksi teks/tabel PDF (dependensi berat)."),
    ("pdfminer.six", "pdfminer", "Files / Office / Document", "pure", "EXPERIMENTAL",
     "Parser PDF tingkat rendah."),
    ("odfpy", "odf", "Files / Office / Document", "pure", "COMPATIBLE",
     "Baca/tulis OpenDocument."),
    ("xlrd", "xlrd", "Files / Office / Document", "pure", "COMPATIBLE",
     "Baca Excel .xls (legacy)."),
    ("xlwt", "xlwt", "Files / Office / Document", "pure", "COMPATIBLE",
     "Tulis Excel .xls (legacy)."),
    ("csvkit", "csvkit", "Files / Office / Document", "pure", "COMPATIBLE",
     "Toolkit CSV baris-perintah."),
    ("tablib", "tablib", "Files / Office / Document", "pure", "COMPATIBLE",
     "Konversi format data (CSV/JSON/Excel/YAML)."),
    ("parsedatetime", "parsedatetime", "Files / Office / Document", "pure", "COMPATIBLE",
     "Parse waktu natural."),
    ("charset-normalizer", "charset_normalizer", "Files / Office / Document", "pure", "COMPATIBLE",
     "Deteksi encoding teks."),
    ("chardet", "chardet", "Files / Office / Document", "pure", "COMPATIBLE",
     "Deteksi encoding (dep requests)."),
    ("ftfy", "ftfy", "Files / Office / Document", "pure", "COMPATIBLE",
     "Perbaiki teks Unicode rusak."),
    ("python-magic", "magic", "Files / Office / Document", "native", "EXPERIMENTAL",
     "Deteksi tipe file via libmagic (native)."),
    ("filetype", "filetype", "Files / Office / Document", "pure", "COMPATIBLE",
     "Deteksi tipe file dari magic bytes (murni-Python)."),
    ("send2trash", "send2trash", "Files / Office / Document", "pure", "COMPATIBLE",
     "Hapus file ke recycle bin."),
    ("pyzipper", "pyzipper", "Files / Office / Document", "pure", "COMPATIBLE",
     "ZIP dengan enkripsi AES (baca/tulis)."),
    ("rarfile", "rarfile", "Files / Office / Document", "pure", "EXPERIMENTAL",
     "Baca RAR (butuh binary unrar)."),
    ("py7zr", "py7zr", "Files / Office / Document", "pure", "COMPATIBLE",
     "Baca/tulis 7z murni-Python."),
    ("patool", "patool", "Files / Office / Document", "pure", "COMPATIBLE",
     "Wrapper archive multi-format."),
    ("babel", "babel", "Files / Office / Document", "pure", "COMPATIBLE",
     "i18n/l10n (dep Flask)."),
    ("markdown", "markdown", "Files / Office / Document", "pure", "COMPATIBLE",
     "Konversi Markdown → HTML."),
    ("markdownify", "markdownify", "Files / Office / Document", "pure", "COMPATIBLE",
     "HTML → Markdown."),
    ("docutils", "docutils", "Files / Office / Document", "pure", "COMPATIBLE",
     "reStructuredText → berbagai format."),
    ("mistune", "mistune", "Files / Office / Document", "pure", "COMPATIBLE",
     "Markdown parser cepat."),
    ("weasyprint", "weasyprint", "Files / Office / Document", "pure", "INCOMPATIBLE",
     "HTML→PDF butuh library sistem (pango dll) — di luar jangkauan."),

    # ---------------- Database / Storage (25) ----------------
    ("sqlalchemy", "sqlalchemy", "Database / Storage", "pure", "COMPATIBLE",
     "ORM & SQL toolkit."),
    ("sqlmodel", "sqlmodel", "Database / Storage", "pure", "COMPATIBLE",
     "SQLAlchemy + Pydantic."),
    ("peewee", "peewee", "Database / Storage", "pure", "COMPATIBLE",
     "ORM kecil."),
    ("pymongo", "pymongo", "Database / Storage", "native", "EXPERIMENTAL",
     "MongoDB driver (C extension)."),
    ("redis", "redis", "Database / Storage", "pure", "COMPATIBLE",
     "Redis client (butuh server Redis)."),
    ("psycopg2-binary", "psycopg2", "Database / Storage", "native", "EXPERIMENTAL",
     "PostgreSQL driver (native — butuh libpq; wheel Android belum tentu ada)."),
    ("pymysql", "pymysql", "Database / Storage", "pure", "COMPATIBLE",
     "MySQL driver murni-Python."),
    ("aiosqlite", "aiosqlite", "Database / Storage", "pure", "COMPATIBLE",
     "SQLite async untuk asyncio."),
    ("tinydb", "tinydb", "Database / Storage", "pure", "COMPATIBLE",
     "Database JSON kecil tanpa server."),
    ("pickledb", "pickledb", "Database / Storage", "pure", "COMPATIBLE",
     "Key-value store sederhana."),
    ("diskcache", "diskcache", "Database / Storage", "pure", "COMPATIBLE",
     "Cache berbasis disk (SQLite)."),
    ("joblib", "joblib", "Database / Storage", "pure", "COMPATIBLE",
     "Persistensi objek + parallel (dep scikit-learn)."),
    ("cloudpickle", "cloudpickle", "Database / Storage", "pure", "COMPATIBLE",
     "Pickle untuk fungsi/closure."),
    ("dill", "dill", "Database / Storage", "pure", "COMPATIBLE",
     "Pickle extended."),
    ("zstandard", "zstandard", "Database / Storage", "native", "EXPERIMENTAL",
     "Kompresi zstd (C extension)."),
    ("lz4", "lz4", "Database / Storage", "native", "EXPERIMENTAL",
     "Kompresi LZ4 (C extension)."),
    ("python-snappy", "snappy", "Database / Storage", "native", "EXPERIMENTAL",
     "Kompresi Snappy (native)."),
    ("blosc", "blosc", "Database / Storage", "native", "EXPERIMENTAL",
     "Kompresi blosc (native)."),
    ("minio", "minio", "Database / Storage", "pure", "COMPATIBLE",
     "S3-compatible client."),
    ("boto3", "boto3", "Database / Storage", "pure", "COMPATIBLE",
     "AWS SDK (perlu kredensial)."),
    ("paramiko", "paramiko", "Database / Storage", "pure", "EXPERIMENTAL",
     "SSH/SFTP client (cryptography native)."),
    ("fabric", "fabric", "Database / Storage", "pure", "COMPATIBLE",
     "Deployment via SSH (di atas paramiko)."),
    ("sqlitedict", "sqlitedict", "Database / Storage", "pure", "COMPATIBLE",
     "Dict persisten di SQLite."),
    ("dataset", "dataset", "Database / Storage", "pure", "COMPATIBLE",
     "Database untuk manusia (di atas SQLAlchemy)."),
    ("ormar", "ormar", "Database / Storage", "pure", "EXPERIMENTAL",
     "ORM async modern (dependensi banyak)."),

    # ---------------- Automation / Scripting (25) ----------------
    ("invoke", "invoke", "Automation / Scripting", "pure", "COMPATIBLE",
     "Task runner Pythonic."),
    ("nox", "nox", "Automation / Scripting", "pure", "COMPATIBLE",
     "Automation test environments."),
    ("watchfiles", "watchfiles", "Automation / Scripting", "native", "EXPERIMENTAL",
     "File watcher native (rust)."),
    ("crontab", "crontab", "Automation / Scripting", "pure", "COMPATIBLE",
     "Manipulasi crontab."),
    ("apscheduler", "apscheduler", "Automation / Scripting", "pure", "COMPATIBLE",
     "Scheduler advanced."),
    ("python-crontab", "crontab", "Automation / Scripting", "pure", "COMPATIBLE",
     "Alias crontab."),
    ("fabric2", "fabric", "Automation / Scripting", "pure", "COMPATIBLE",
     "Alias fabric."),
    ("pypeln", "pypeln", "Automation / Scripting", "pure", "COMPATIBLE",
     "Pipeline data concurrent."),
    ("jinjalint", "jinjalint", "Automation / Scripting", "pure", "COMPATIBLE",
     "Linter template Jinja."),
    ("cookiecutter", "cookiecutter", "Automation / Scripting", "pure", "COMPATIBLE",
     "Scaffold project dari template."),
    ("pystache", "pystache", "Automation / Scripting", "pure", "COMPATIBLE",
     "Mustache template."),
    ("cheetah3", "cheetah", "Automation / Scripting", "pure", "COMPATIBLE",
     "Template engine Cheetah."),
    ("mako", "mako", "Automation / Scripting", "pure", "COMPATIBLE",
     "Template engine Mako."),
    ("ruamel.yaml", "ruamel.yaml", "Automation / Scripting", "pure", "COMPATIBLE",
     "YAML round-trip (dep banyak tool)."),
    ("docker", "docker", "Automation / Scripting", "pure", "INCOMPATIBLE",
     "Butuh Docker daemon — out of scope ZCODE."),
    ("kubernetes", "kubernetes", "Automation / Scripting", "pure", "COMPATIBLE",
     "K8s client (butuh cluster)."),
    ("ansible", "ansible", "Automation / Scripting", "pure", "EXPERIMENTAL",
     "Automation config (berat, butuh SSH)."),
    ("pygithub", "github", "Automation / Scripting", "pure", "COMPATIBLE",
     "GitHub API client."),
    ("gitpython", "git", "Automation / Scripting", "pure", "COMPATIBLE",
     "Git via Python (butuh binary git)."),
    ("pre-commit", "pre_commit", "Automation / Scripting", "pure", "COMPATIBLE",
     "Git hooks manager."),
    ("black", "black", "Automation / Scripting", "pure", "COMPATIBLE",
     "Python code formatter."),
    ("isort", "isort", "Automation / Scripting", "pure", "COMPATIBLE",
     "Import sorter."),
    ("autoflake", "autoflake", "Automation / Scripting", "pure", "COMPATIBLE",
     "Hapus import tidak terpakai."),
    ("yapf", "yapf", "Automation / Scripting", "pure", "COMPATIBLE",
     "Formatter ala Google."),
    ("autopep8", "autopep8", "Automation / Scripting", "pure", "COMPATIBLE",
     "Perbaiki gaya PEP8 otomatis."),

    # ---------------- Testing / Quality / Debugging (25) ----------------
    ("pytest", "pytest", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Framework testing standar."),
    ("unittest2", "unittest2", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Backport unittest."),
    ("hypothesis", "hypothesis", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Property-based testing."),
    ("coverage", "coverage", "Testing / Quality / Debugging", "native", "EXPERIMENTAL",
     "Cek cakupan kode (C extension — cek wheel)."),
    ("pytest-cov", "pytest_cov", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Plugin coverage utk pytest."),
    ("pytest-mock", "pytest_mock", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Mocking di pytest."),
    ("pytest-asyncio", "pytest_asyncio", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Async testing pytest."),
    ("pytest-xdist", "xdist", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Paralelisasi pytest."),
    ("tox", "tox", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Test environment automation."),
    ("mock", "mock", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Mocking (stdlib sejak 3.3)."),
    ("responses", "responses", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Mock requests."),
    ("vcrpy", "vcr", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Record & replay HTTP."),
    ("freezegun", "freezegun", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Frozen time di test."),
    ("faker", "faker", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Generate data palsu realistis."),
    ("factory-boy", "factory", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Factory fixtures."),
    ("pdbpp", "pdbpp", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Debugger pdb++ (interaktif di terminal)."),
    ("ipdb", "ipdb", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "ipython debugger (butuh ipython)."),
    ("py-spy", "py_spy", "Testing / Quality / Debugging", "native", "INCOMPATIBLE",
     "Sampling profiler — butuh PTY/kernel — out of scope."),
    ("memory-profiler", "memory_profiler", "Testing / Quality / Debugging", "pure", "EXPERIMENTAL",
     "Profil memori per baris."),
    ("line-profiler", "line_profiler", "Testing / Quality / Debugging", "native", "EXPERIMENTAL",
     "Profil per baris (C extension)."),
    ("flake8", "flake8", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Linter PEP8."),
    ("ruff", "ruff", "Testing / Quality / Debugging", "native", "EXPERIMENTAL",
     "Linter Rust super cepat (binary wheel — cek)."),
    ("mypy", "mypy", "Testing / Quality / Debugging", "pure", "EXPERIMENTAL",
     "Static type checker (berat di device kecil)."),
    ("pyright", "pyright", "Testing / Quality / Debugging", "pure", "EXPERIMENTAL",
     "Type checker berbasis Node — butuh nodejs, tidak didukung."),
    ("bandit", "bandit", "Testing / Quality / Debugging", "pure", "COMPATIBLE",
     "Security linter untuk kode Python."),

    # ---------------- Image / Audio / Media (25) ----------------
    ("pillow", "PIL", "Image / Audio / Media", "native", "TESTED",
     "Pemrosesan gambar (resize, filter, format)."),
    ("opencv-python", "cv2", "Image / Audio / Media", "native", "EXPERIMENTAL",
     "Computer vision (native besar; versi headless bisa dicoba)."),
    ("imageio", "imageio", "Image / Audio / Media", "pure", "COMPATIBLE",
     "I/O gambar multi-format."),
    ("imageio-ffmpeg", "imageio_ffmpeg", "Image / Audio / Media", "native", "EXPERIMENTAL",
     "FFmpeg binary plugin — besar, tidak dibundel."),
    ("av", "av", "Image / Audio / Media", "native", "EXPERIMENTAL",
     "PyAV — binding FFmpeg (native besar; butuh wheel Android)."),
    ("imagehash", "imagehash", "Image / Audio / Media", "pure", "COMPATIBLE",
     "Perceptual image hashing (butuh Pillow)."),
    ("moviepy", "moviepy", "Image / Audio / Media", "pure", "EXPERIMENTAL",
     "Editing video (butuh ffmpeg)."),
    ("pydub", "pydub", "Image / Audio / Media", "pure", "COMPATIBLE",
     "Manipulasi audio (butuh ffmpeg/avconv untuk banyak format)."),
    ("soundfile", "soundfile", "Image / Audio / Media", "native", "EXPERIMENTAL",
     "Baca/tulis WAV/FLAC (libsndfile native)."),
    ("audioread", "audioread", "Image / Audio / Media", "pure", "COMPATIBLE",
     "Decode audio via backend."),
    ("wavio", "wavio", "Image / Audio / Media", "pure", "COMPATIBLE",
     "Baca/tulis WAV via numpy (murni-Python)."),
    ("pyaudio", "pyaudio", "Image / Audio / Media", "native", "INCOMPATIBLE",
     "Butuh PortAudio system — tidak didukung di Chaquopy."),
    ("pygame", "pygame", "Image / Audio / Media", "native", "INCOMPATIBLE",
     "Butuh SDL — ranah ZPLAY, bukan Chaquopy."),
    ("pygame-ce", "pygame", "Image / Audio / Media", "native", "INCOMPATIBLE",
     "Community edition — tetap butuh SDL."),
    ("mutagen", "mutagen", "Image / Audio / Media", "pure", "COMPATIBLE",
     "Baca/tulis tag audio MP3/FLAC/OGG (murni-Python)."),
    ("qrcode", "qrcode", "Image / Audio / Media", "pure", "COMPATIBLE",
     "Generate QR code (pakai Pillow)."),
    ("pyzbar", "pyzbar", "Image / Audio / Media", "native", "EXPERIMENTAL",
     "Baca barcode/QR (libzbar native)."),
    ("exifread", "exifread", "Image / Audio / Media", "pure", "COMPATIBLE",
     "Baca metadata EXIF."),
    ("piexif", "piexif", "Image / Audio / Media", "pure", "COMPATIBLE",
     "Tulis/baca EXIF (untuk Pillow)."),
    ("colour", "colour", "Image / Audio / Media", "pure", "COMPATIBLE",
     "Color science (perlu numpy)."),
    ("colorthief", "colorthief", "Image / Audio / Media", "pure", "COMPATIBLE",
     "Ekstrak palet warna dominan."),
    ("gif", "gif", "Image / Audio / Media", "pure", "COMPATIBLE",
     "Buat GIF sederhana."),
    ("tesserocr", "tesserocr", "Image / Audio / Media", "native", "INCOMPATIBLE",
     "OCR butuh binary tesseract — tidak didukung."),
    ("pytesseract", "pytesseract", "Image / Audio / Media", "pure", "INCOMPATIBLE",
     "Wrapper tesseract — binary tidak tersedia di Android."),
    ("face_recognition", "face_recognition", "Image / Audio / Media", "native", "INCOMPATIBLE",
     "Butuh dlib — kemungkinan tidak ada wheel Android."),

    # ---------------- AI / ML / NLP (25) ----------------
    ("transformers", "transformers", "AI / ML / NLP", "pure", "EXPERIMENTAL",
     "Model HuggingFace (berat; model kecil bisa)."),
    ("torch", "torch", "AI / ML / NLP", "native", "INCOMPATIBLE",
     "PyTorch butuh wheel Android khusus + bootstrap — STANDALONE REQUIRED."),
    ("tensorflow", "tensorflow", "AI / ML / NLP", "native", "INCOMPATIBLE",
     "TensorFlow desktop tidak untuk Android in-process; pakai tflite-runtime."),
    ("tflite-runtime", "tflite_runtime", "AI / ML / NLP", "native", "EXPERIMENTAL",
     "TensorFlow Lite runtime (didukung Chaquopy FAQ)."),
    ("keras", "keras", "AI / ML / NLP", "pure", "EXPERIMENTAL",
     "High-level NN API (butuh backend)."),
    ("onnxruntime", "onnxruntime", "AI / ML / NLP", "native", "EXPERIMENTAL",
     "Inference ONNX (cek wheel Android)."),
    ("xgboost", "xgboost", "AI / ML / NLP", "native", "EXPERIMENTAL",
     "Gradient boosting (native; wheel Android?)."),
    ("lightgbm", "lightgbm", "AI / ML / NLP", "native", "EXPERIMENTAL",
     "Gradient boosting ringan (native)."),
    ("catboost", "catboost", "AI / ML / NLP", "native", "EXPERIMENTAL",
     "Gradient boosting (native besar)."),
    ("spacy", "spacy", "AI / ML / NLP", "native", "EXPERIMENTAL",
     "NLP industrial (model terpisah, native)."),
    ("gensim", "gensim", "AI / ML / NLP", "pure", "EXPERIMENTAL",
     "Topic modeling (butuh scipy)."),
    ("jieba", "jieba", "AI / ML / NLP", "pure", "COMPATIBLE",
     "Segmentasi kata Mandarin."),
    ("konlpy", "konlpy", "AI / ML / NLP", "pure", "EXPERIMENTAL",
     "NLP Korea (butuh Java/JVM)."),
    ("sentencepiece", "sentencepiece", "AI / ML / NLP", "native", "EXPERIMENTAL",
     "Tokenisasi subword (C++ native)."),
    ("tokenizers", "tokenizers", "AI / ML / NLP", "native", "EXPERIMENTAL",
     "Tokenizers Rust (HuggingFace)."),
    ("safetensors", "safetensors", "AI / ML / NLP", "native", "EXPERIMENTAL",
     "Format tensor aman (native)."),
    ("sklearn-crfsuite", "sklearn_crfsuite", "AI / ML / NLP", "pure", "EXPERIMENTAL",
     "CRF untuk NER (butuh python-crfsuite native)."),
    ("python-crfsuite", "pycrfsuite", "AI / ML / NLP", "native", "EXPERIMENTAL",
     "CRFsuite binding (native)."),
    ("openai", "openai", "AI / ML / NLP", "pure", "COMPATIBLE",
     "OpenAI API client (butuh internet + kunci)."),
    ("anthropic", "anthropic", "AI / ML / NLP", "pure", "COMPATIBLE",
     "Anthropic Claude API client."),
    ("langchain", "langchain", "AI / ML / NLP", "pure", "EXPERIMENTAL",
     "Framework LLM apps (dependensi banyak)."),
    ("llama-cpp-python", "llama_cpp", "AI / ML / NLP", "native", "EXPERIMENTAL",
     "LLM lokal via llama.cpp (perlu build Android — belum pasti)."),
    ("whisper", "whisper", "AI / ML / NLP", "pure", "INCOMPATIBLE",
     "Speech-to-text butuh torch — ikut torch (STANDALONE)."),
    ("sentence-transformers", "sentence_transformers", "AI / ML / NLP", "pure", "EXPERIMENTAL",
     "Embedding (butuh torch)."),
    ("imblearn", "imblearn", "AI / ML / NLP", "pure", "COMPATIBLE",
     "Resampling data tidak seimbang (di atas scikit-learn)."),

    # ---------------- GUI / Games / App Framework (15) ----------------
    ("tkinter", "tkinter", "GUI / Games / App Framework", "pure", "INCOMPATIBLE",
     "Butuh Tk — tidak ada di Android Chaquopy."),
    ("pyqt5", "PyQt5", "GUI / Games / App Framework", "native", "INCOMPATIBLE",
     "Butuh Qt native — STANDALONE REQUIRED."),
    ("pyside6", "PySide6", "GUI / Games / App Framework", "native", "INCOMPATIBLE",
     "Butuh Qt6 native — STANDALONE REQUIRED."),
    ("kivy", "kivy", "GUI / Games / App Framework", "native", "INCOMPATIBLE",
     "Butuh bootstrap APK sendiri — STANDALONE REQUIRED."),
    ("appjar", "appJar", "GUI / Games / App Framework", "pure", "INCOMPATIBLE",
     "Berbasis tkinter."),
    ("arcade", "arcade", "GUI / Games / App Framework", "native", "INCOMPATIBLE",
     "Game framework butuh OpenGL desktop."),
    ("pyglet", "pyglet", "GUI / Games / App Framework", "native", "INCOMPATIBLE",
     "Butuh windowing desktop."),
    ("panda3d", "panda3d", "GUI / Games / App Framework", "native", "INCOMPATIBLE",
     "Game engine C++ — tidak untuk Android in-process."),
    ("curses", "curses", "GUI / Games / App Framework", "pure", "INCOMPATIBLE",
     "TUI butuh terminal penuh — ZCODE punya terminal sendiri (via print/ANSI)."),
    ("blessed", "blessed", "GUI / Games / App Framework", "pure", "COMPATIBLE",
     "Terminal styling (di atas curses — sebagian fitur terbatas)."),
    ("textual", "textual", "GUI / Games / App Framework", "pure", "EXPERIMENTAL",
     "TUI framework modern (butuh terminal penuh)."),
    ("prompt_toolkit", "prompt_toolkit", "GUI / Games / App Framework", "pure", "COMPATIBLE",
     "Prompt interaktif kaya (dipakai IPython)."),
    ("ipython", "IPython", "GUI / Games / App Framework", "pure", "EXPERIMENTAL",
     "REPL canggih (berat; ZCODE punya REPL sendiri)."),
    ("jupyter_core", "jupyter_core", "GUI / Games / App Framework", "pure", "COMPATIBLE",
     "Kernel jupyter core (untuk integrasi)."),
    ("cocos2d", "cocos2d", "GUI / Games / App Framework", "native", "INCOMPATIBLE",
     "Game engine — butuh bootstrap khusus."),

    # ---------------- Security / Cryptography (15) ----------------
    ("cryptography", "cryptography", "Security / Cryptography", "native", "EXPERIMENTAL",
     "Primitif kripto (OpenSSL native — cek wheel Chaquopy)."),
    ("pycryptodome", "Crypto", "Security / Cryptography", "native", "EXPERIMENTAL",
     "Kripto murni-C (wheel Android?)."),
    ("bcrypt", "bcrypt", "Security / Cryptography", "native", "EXPERIMENTAL",
     "Hash password (C extension)."),
    ("argon2-cffi", "argon2", "Security / Cryptography", "native", "EXPERIMENTAL",
     "Argon2 (C extension)."),
    ("passlib", "passlib", "Security / Cryptography", "pure", "COMPATIBLE",
     "Password hashing library."),
    ("jwt", "jwt", "Security / Cryptography", "pure", "COMPATIBLE",
     "PyJWT — JSON Web Tokens."),
    ("python-jose", "jose", "Security / Cryptography", "pure", "COMPATIBLE",
     "JOSE implementation."),
    ("oauthlib", "oauthlib", "Security / Cryptography", "pure", "COMPATIBLE",
     "OAuth 1/2 framework."),
    ("authlib", "authlib", "Security / Cryptography", "pure", "COMPATIBLE",
     "OAuth/OpenID modern."),
    ("asn1crypto", "asn1crypto", "Security / Cryptography", "pure", "COMPATIBLE",
     "Parser ASN.1 murni-Python (dep cryptography)."),
    ("keyring", "keyring", "Security / Cryptography", "pure", "EXPERIMENTAL",
     "Credential store (backend Android?)."),
    ("pyotp", "pyotp", "Security / Cryptography", "pure", "COMPATIBLE",
     "TOTP/HOTP two-factor authentication."),
    ("hashids", "hashids", "Security / Cryptography", "pure", "COMPATIBLE",
     "Hash angka → string pendek (bukan kriptografi)."),
    ("trustme", "trustme", "Security / Cryptography", "pure", "COMPATIBLE",
     "Generate TLS cert untuk testing lokal."),
    ("nacl", "nacl", "Security / Cryptography", "native", "EXPERIMENTAL",
     "libsodium binding (native)."),
]

# ---------------------------------------------------------------------------
# Detail lengkap untuk package utama (SPEC §19) — status TESTED/prioritas tinggi
# ---------------------------------------------------------------------------
# key: canonical name → dict tambahan
RICH = {
    "requests": {
        "testedVersion": "2.32.3", "python": ["3.11"], "abis": [],
        "useCases": ["HTTP GET/POST", "akses REST API", "download file"],
        "works": ["requests.get/post", "session & header", "HTTPS via certifi"],
        "doesNotWork": ["proxies yang butuh auth system-level"],
        "risks": ["jalur HTTPS butuh certifi ter-update"],
        "smokeTest": "requests_basic",
        "license": "Apache-2.0", "publisher": "Kenneth Reitz / PSF",
        "source": "https://pypi.org/project/requests/",
    },
    "httpx": {
        "testedVersion": "0.27.2", "python": ["3.11"], "abis": [],
        "useCases": ["HTTP sync/async", "HTTP/2", "client modern"],
        "works": ["Client sync & async", "streaming response"],
        "doesNotWork": ["HTTP/2 di sebagian server (dependensi h2)"],
        "risks": ["pakai httpcore/h11 — pastikan dependency ikut"],
        "smokeTest": "httpx_basic",
        "license": "BSD-3-Clause", "publisher": "Encode",
        "source": "https://pypi.org/project/httpx/",
    },
    "flask": {
        "testedVersion": "3.0.3", "python": ["3.11"], "abis": [],
        "useCases": ["web server lokal", "App Mode Flask + WebView", "API kecil"],
        "works": ["route & render", "JSON API", "development server"],
        "doesNotWork": ["HTTPS production", "multiprocessing workers"],
        "risks": ["server dev saja; untuk publik pakai waitress"],
        "smokeTest": "flask_app",
        "license": "BSD-3-Clause", "publisher": "Pallets",
        "source": "https://pypi.org/project/Flask/",
    },
    "beautifulsoup4": {
        "testedVersion": "4.12.3", "python": ["3.11"], "abis": [],
        "useCases": ["scraping HTML", "parse XML", "bersihkan markup"],
        "works": ["BeautifulSoup(html)", "find/find_all", "get_text"],
        "doesNotWork": ["parsing super cepat (pakai lxml untuk itu)"],
        "risks": ["butuh html5lib/lxml untuk beberapa parser — cukup bawaan"],
        "smokeTest": "bs4_parse",
        "license": "MIT", "publisher": "Leonard Richardson",
        "source": "https://pypi.org/project/beautifulsoup4/",
    },
    "tqdm": {
        "testedVersion": "4.66.4", "python": ["3.11"], "abis": [],
        "useCases": ["progress bar loop", "download progress"],
        "works": ["tqdm(range(...))", "write() untuk log"],
        "doesNotWork": ["GUI progress"],
        "risks": ["di terminal ZCODE pakai mode plain (ANSI terbatas)"],
        "smokeTest": "tqdm_basic",
        "license": "MPL-2.0 / MIT", "publisher": "Casper da Costa-Luis",
        "source": "https://pypi.org/project/tqdm/",
    },
    "rich": {
        "testedVersion": "13.7.1", "python": ["3.11"], "abis": [],
        "useCases": ["output berwarna", "tabel", "panel & tree"],
        "works": ["print(rich)", "Table", "Console"],
        "doesNotWork": ["live display yang butuh terminal penuh (sebagian)"],
        "risks": ["ANSI di terminal ZCODE diproses — warna tampil"],
        "smokeTest": "rich_render",
        "license": "MIT", "publisher": "Will McGugan",
        "source": "https://pypi.org/project/rich/",
    },
    "bokeh": {
        "testedVersion": "3.3.4", "python": ["3.11"], "abis": [],
        "useCases": ["plot interaktif", "standalone HTML", "contour plot"],
        "works": [
            "DEVICE VERIFIED 2026-08-20: install dependency-correct dan auto-relaunch pada INFINIX X6532C/API34/armeabi-v7a.",
            "Direct import bokeh 3.3.4 + contourpy 1.0.5 + numpy 1.26.2 + pandas 2.1.3 berhasil setelah relaunch.",
            "Standalone HTML dan contour HTML 646935 byte berhasil, exit code 0.",
        ],
        "doesNotWork": [
            "Bokeh 3.4+ butuh contourpy>=1.2; CPython 3.11 ARMv7 hanya punya 1.0.5."
        ],
        "risks": [
            "Package native/dependency wajib memakai process baru setelah install; ZCODE menangani ini dengan auto-relaunch.",
            "Pandas/NumPy membuat instalasi besar pada perangkat rendah RAM.",
        ],
        "smokeTest": None,
        "license": "BSD-3-Clause", "publisher": "Bokeh Team / NumFOCUS",
        "source": "https://pypi.org/project/bokeh/3.3.4/",
    },
    "openpyxl": {
        "testedVersion": "3.1.5", "python": ["3.11"], "abis": [],
        "useCases": ["baca/tulis Excel", "laporan data", "template xlsx"],
        "works": ["load_workbook", "cell value", "save"],
        "doesNotWork": ["macro Excel (xlsm terbatas)", "format super kompleks"],
        "risks": ["file besar makan RAM"],
        "smokeTest": "openpyxl_roundtrip",
        "license": "MIT", "publisher": "Eric Gazoni / Charlie Clark",
        "source": "https://pypi.org/project/openpyxl/",
    },
    "numpy": {
        "testedVersion": "1.26.4", "python": ["3.11"],
        "abis": ["armeabi-v7a", "arm64-v8a", "x86_64"],
        "useCases": ["array numerik", "matriks", "fondasi pandas/matplotlib"],
        "works": ["np.arange/array", "operasi vektor", "np.linalg"],
        "doesNotWork": ["BLAS/LAPACK berkinerja penuh (wheel Chaquopy tersedia tapi terbatas)"],
        "risks": ["wheel native ~8-15MB; device 16KB page bisa gagal load versi lama"],
        "smokeTest": "numpy_basic",
        "license": "BSD-3-Clause", "publisher": "NumPy developers",
        "source": "https://pypi.org/project/numpy/",
    },
    "matplotlib": {
        "testedVersion": "3.6.0", "python": ["3.11"],
        "abis": ["armeabi-v7a", "arm64-v8a", "x86_64"],
        "useCases": ["chart", "data visualization", "savefig PNG"],
        "works": ["backend Agg", "savefig('out.png')", "plot/scatter/bar"],
        "doesNotWork": ["GUI window interaktif", "backend Tk/Qt"],
        "risks": ["storage besar (±20MB terinstall)", "ram agak tinggi"],
        "smokeTest": "matplotlib_agg_png",
        "license": "PSF-2.0", "publisher": "Matplotlib Development Team",
        "source": "https://pypi.org/project/matplotlib/",
    },
    "pillow": {
        "testedVersion": "10.3.0", "python": ["3.11"],
        "abis": ["armeabi-v7a", "arm64-v8a", "x86_64"],
        "useCases": ["edit gambar", "konversi format", "thumbnail"],
        "works": ["Image.open/resize/save", "filter", "format JPEG/PNG"],
        "doesNotWork": ["format eksotis (WEBP sebagian)"],
        "risks": ["native tapi ringan; libjpeg dibundel wheel"],
        "smokeTest": "pillow_roundtrip",
        "license": "HPND / MIT-CMU", "publisher": "Jeffrey A. Clark (Pillow)",
        "source": "https://pypi.org/project/pillow/",
    },
    "scipy": {
        "testedVersion": None, "python": ["3.11"],
        "abis": ["armeabi-v7a", "arm64-v8a", "x86_64"],
        "useCases": ["optimasi", "statistik", "sinyal"],
        "works": ["scipy.optimize", "scipy.stats", "scipy.fft"],
        "doesNotWork": ["bagian yang butuh BLAS/LAPACK penuh"],
        "risks": ["berat (storage & RAM)"],
        "smokeTest": None, "license": "BSD-3-Clause", "publisher": "SciPy developers",
        "source": "https://pypi.org/project/scipy/",
    },
    "pandas": {
        "testedVersion": None, "python": ["3.11"],
        "abis": ["armeabi-v7a", "arm64-v8a", "x86_64"],
        "useCases": ["DataFrame", "analisis tabular", "CSV/Excel"],
        "works": ["pd.read_csv", "groupby", "to_excel"],
        "doesNotWork": ["dataset sangat besar di RAM kecil"],
        "risks": ["berat di HP <4GB RAM"],
        "smokeTest": None, "license": "BSD-3-Clause", "publisher": "Pandas contributors",
        "source": "https://pypi.org/project/pandas/",
    },
    "lxml": {
        "testedVersion": None, "python": ["3.11"],
        "abis": ["armeabi-v7a", "arm64-v8a", "x86_64"],
        "useCases": ["parsing XML/HTML cepat"],
        "works": ["etree", "html.fromstring"],
        "doesNotWork": ["fitur yang butuh libxslt versi khusus"],
        "risks": ["native; cek wheel Chaquopy"],
        "smokeTest": None, "license": "BSD-3-Clause", "publisher": "lxml dev team",
        "source": "https://pypi.org/project/lxml/",
    },
    "pydantic": {
        "testedVersion": None, "python": ["3.11"],
        "abis": [],
        "useCases": ["validasi data", "settings", "API models"],
        "works": ["BaseModel", "validators", "JSON schema"],
        "doesNotWork": ["pydantic v1 API lama (pakai v2)"],
        "risks": ["pydantic-core native — cek wheel"],
        "smokeTest": None, "license": "MIT", "publisher": "Samuel Colvin",
        "source": "https://pypi.org/project/pydantic/",
    },
    "pyyaml": {
        "testedVersion": None, "python": ["3.11"], "abis": [],
        "useCases": ["konfigurasi YAML", "data serialization"],
        "works": ["yaml.safe_load", "yaml.dump"],
        "doesNotWork": ["YAML 1.2 penuh (sebagian)"],
        "risks": ["minimal"],
        "smokeTest": None, "license": "MIT", "publisher": "Kirill Simonov",
        "source": "https://pypi.org/project/PyYAML/",
    },
    "python-dateutil": {
        "testedVersion": None, "python": ["3.11"], "abis": [],
        "useCases": ["parse tanggal", "relativedelta"],
        "works": ["dateutil.parser", "relativedelta"],
        "doesNotWork": [],
        "risks": ["minimal"],
        "smokeTest": None, "license": "Apache-2.0 / BSD-3-Clause", "publisher": "dateutil contributors",
        "source": "https://pypi.org/project/python-dateutil/",
    },
    "regex": {
        "testedVersion": None, "python": ["3.11"],
        "abis": ["armeabi-v7a", "arm64-v8a", "x86_64"],
        "useCases": ["regex tingkat lanjut"],
        "works": ["regex.search", "fuzzy matching"],
        "doesNotWork": [],
        "risks": ["C extension — cek wheel Chaquopy"],
        "smokeTest": None, "license": "Python-2.0", "publisher": "Matthew Barnett",
        "source": "https://pypi.org/project/regex/",
    },
    "colorama": {
        "testedVersion": None, "python": ["3.11"], "abis": [],
        "useCases": ["warna ANSI lintas platform"],
        "works": ["Fore/Back/Style"],
        "doesNotWork": [],
        "risks": ["di terminal ZCODE, ANSI sudah diproses"],
        "smokeTest": None, "license": "BSD-3-Clause", "publisher": "Arnon Yaari",
        "source": "https://pypi.org/project/colorama/",
    },
    "click": {
        "testedVersion": None, "python": ["3.11"], "abis": [],
        "useCases": ["CLI argument parser"],
        "works": ["@click.command", "options & args"],
        "doesNotWork": ["prompt interaktif terbatas di ZCODE"],
        "risks": ["minimal"],
        "smokeTest": None, "license": "BSD-3-Clause", "publisher": "Pallets",
        "source": "https://pypi.org/project/click/",
    },
    "certifi": {
        "testedVersion": None, "python": ["3.11"], "abis": [],
        "useCases": ["CA bundle HTTPS"],
        "works": ["certifi.where()"],
        "doesNotWork": [],
        "risks": ["update berkala untuk keamanan"],
        "smokeTest": None, "license": "MPL-2.0", "publisher": "Certifi authors",
        "source": "https://pypi.org/project/certifi/",
    },
}

# ---------------------------------------------------------------------------
# Smoke test manifests (SPEC §9) — package utama
# ---------------------------------------------------------------------------
SMOKE_TESTS = {
    "requests": [{"name": "import requests", "type": "IMPORT", "target": "requests"},
                 {"name": "requests.get smoke", "type": "BASIC_API",
                  "code": "import requests; assert requests.__version__"}],
    "httpx": [{"name": "import httpx", "type": "IMPORT", "target": "httpx"},
              {"name": "httpx client", "type": "BASIC_API",
               "code": "import httpx; c = httpx.Client(); assert c is not None; c.close()"}],
    "flask": [{"name": "import flask", "type": "IMPORT", "target": "flask"},
              {"name": "flask app", "type": "BASIC_API",
               "code": "from flask import Flask; app = Flask(__name__); assert app is not None"}],
    "beautifulsoup4": [{"name": "import bs4", "type": "IMPORT", "target": "bs4"},
                       {"name": "bs4 parse", "type": "BASIC_API",
                        "code": "from bs4 import BeautifulSoup; s = BeautifulSoup('<p>x</p>', 'html.parser'); assert s.p is not None"}],
    "tqdm": [{"name": "import tqdm", "type": "IMPORT", "target": "tqdm"},
             {"name": "tqdm iter", "type": "BASIC_API",
              "code": "from tqdm import tqdm; n = 0; [n for _ in tqdm(range(10), disable=True)]; assert n == 0"}],
    "rich": [{"name": "import rich", "type": "IMPORT", "target": "rich"},
             {"name": "rich render", "type": "BASIC_API",
              "code": "from rich.console import Console; from rich.table import Table; t = Table(); t.add_column('x'); assert len(t.columns) == 1"}],
    "openpyxl": [{"name": "import openpyxl", "type": "IMPORT", "target": "openpyxl"},
                 {"name": "openpyxl roundtrip", "type": "FILE_OUTPUT",
                  "code": "import openpyxl, tempfile, os\n"
                          "wb = openpyxl.Workbook(); ws = wb.active; ws['A1'] = 42\n"
                          "p = os.path.join(tempfile.gettempdir(), 'zcode_smoke.xlsx')\n"
                          "wb.save(p); wb2 = openpyxl.load_workbook(p); assert wb2.active['A1'].value == 42"}],
    "numpy": [{"name": "import numpy", "type": "IMPORT", "target": "numpy"},
              {"name": "numpy basic", "type": "BASIC_API",
               "code": "import numpy as np; a = np.arange(6).reshape(2, 3); assert a.sum() == 15"}],
    "matplotlib": [{"name": "import matplotlib", "type": "IMPORT", "target": "matplotlib"},
                   {"name": "import matplotlib.pyplot", "type": "IMPORT", "target": "matplotlib.pyplot"},
                   {"name": "matplotlib Agg PNG", "type": "FILE_OUTPUT",
                    "code": "import matplotlib\nmatplotlib.use('Agg')\nimport matplotlib.pyplot as plt\n"
                            "import tempfile, os\n"
                            "plt.plot([1, 2, 3]); p = os.path.join(tempfile.gettempdir(), 'zcode_smoke.png')\n"
                            "plt.savefig(p); assert os.path.getsize(p) > 0"}],
    "pillow": [{"name": "import PIL", "type": "IMPORT", "target": "PIL"},
               {"name": "pillow roundtrip", "type": "FILE_OUTPUT",
                "code": "from PIL import Image\nimport tempfile, os\n"
                        "im = Image.new('RGB', (4, 4), 'red')\n"
                        "p = os.path.join(tempfile.gettempdir(), 'zcode_smoke.png')\n"
                        "im.save(p); im2 = Image.open(p); assert im2.size == (4, 4)"}],
}

# tested-manifest: canonical → [versions] (prioritas wheel ZCODE)
TESTED_MANIFEST = {
    "requests": ["2.32.3"],
    "httpx": ["0.27.2"],
    "flask": ["3.0.3"],
    "beautifulsoup4": ["4.12.3"],
    "bokeh": ["3.3.4"],
    "tqdm": ["4.66.4"],
    "rich": ["13.7.1"],
    "openpyxl": ["3.1.5"],
    "numpy": ["1.26.4"],
    "matplotlib": ["3.6.0"],
    "pillow": ["10.3.0"],
}


# Satu sample utama per kartu Library. Sample lengkap tetap hidup di
# SampleLibrary/assets; snippet `example` hanya contoh pendek.
SAMPLE_LINKS = {
    "numpy": "numpy_basics",
    "requests": "requests_api",
    "rich": "rich_table",
    "tqdm": "tqdm_progress",
    "openpyxl": "openpyxl_excel",
    "pillow": "pillow_image",
    "python-docx": "docx_laporan",
    "qrcode": "qr_generator",
    "pandas": "pandas_nilai",
    "sympy": "sympy_aljabar",
    "matplotlib": "matplotlib_chart",
    "httpx": "httpx_api",
    "beautifulsoup4": "beautifulsoup_links",
    "python-pptx": "pptx_presentasi",
    "tinydb": "tinydb_catatan",
    "pyotp": "pyotp_2fa",
    "pyyaml": "pyyaml_config",
}


def canonical(name: str) -> str:
    return name.lower().replace("_", "-").replace(".", "-")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="hanya verifikasi jumlah kategori")
    args = ap.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)

    # validasi duplikat & jumlah per kategori
    seen = set()
    counts = {}
    for name, _imp, cat, _t, _s, _d in CATALOG:
        c = canonical(name)
        if c in seen:
            print(f"!! DUPLIKAT canonical: {c} ({name})")
        seen.add(c)
        counts[cat] = counts.get(cat, 0) + 1

    print("Jumlah package:", len(CATALOG))
    ok_all = True
    for cat, target in CATEGORY_TARGETS.items():
        n = counts.get(cat, 0)
        mark = "OK" if n == target else "!!"
        if n != target:
            ok_all = False
        print(f"  [{mark}] {cat}: {n} (target {target})")

    if args.check:
        sys.exit(0 if (len(CATALOG) == TOTAL_TARGET and ok_all) else 1)

    # ---- packages.json ----
    packages = []
    for name, imp, cat, ptype, status, desc in CATALOG:
        c = canonical(name)
        rich = RICH.get(c, {})
        packages.append({
            "name": name,
            "displayName": rich.get("displayName", name),
            "importName": rich.get("importName", imp),
            "category": cat,
            "type": ptype,
            "status": status,
            "testedVersion": rich.get("testedVersion"),
            "python": rich.get("python", ["3.11"]),
            "abis": rich.get("abis", []),
            "description": rich.get("description", desc),
            "useCases": rich.get("useCases", []),
            "works": rich.get("works", []),
            "doesNotWork": rich.get("doesNotWork", []),
            "dependencies": rich.get("dependencies", []),
            "risks": rich.get("risks", []),
            "smokeTest": rich.get("smokeTest"),
            "license": rich.get("license", ""),
            "publisher": rich.get("publisher", ""),
            "source": rich.get("source", "https://pypi.org/project/%s/" % name),
            "sha256": rich.get("sha256"),
            "sampleId": SAMPLE_LINKS.get(c),
        })
    packages.sort(key=lambda p: (p["category"], p["name"].lower()))
    (OUT / "packages.json").write_text(json.dumps(packages, indent=1, ensure_ascii=False), encoding="utf-8")
    print("✓ packages.json:", len(packages), "package")

    # ---- stdlib.json (Python 3.11 = runtime Chaquopy) ----
    stdlib = sorted(sys.stdlib_module_names)
    (OUT / "stdlib.json").write_text(json.dumps(stdlib, indent=1), encoding="utf-8")
    print("✓ stdlib.json:", len(stdlib), "modul stdlib")

    # ---- smoke-tests.json ----
    (OUT / "smoke-tests.json").write_text(json.dumps(SMOKE_TESTS, indent=1, ensure_ascii=False), encoding="utf-8")
    print("✓ smoke-tests.json:", len(SMOKE_TESTS), "manifest")

    # ---- tested-manifest.json ----
    (OUT / "tested-manifest.json").write_text(json.dumps(TESTED_MANIFEST, indent=1), encoding="utf-8")
    print("✓ tested-manifest.json:", sum(len(v) for v in TESTED_MANIFEST.values()), "versi tested")


if __name__ == "__main__":
    main()
